version: '3.8'

services:
  database:
    build:
      context: ./DataBase
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - "./DataBase/data/db:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
